#server:
#  port: 10011
#spring:
#  application:
#    name: house-gateway
#  cloud:
#    gateway:
#      routes:
#        - id: house-agents-routes
#          uri: lb://HOUSE-AGENTS
#          predicates:
#            - Path=/agent/**
#        - id: house-houses-routes
#          uri: lb://HOUSE-HOUSES
#          predicates:
#            - Path=/properties/**
#      default-filters:
#        - AddResponseHeader=X-Response-Default-MyName, itxuetang9
#
#
#eureka:
#  client:
#    service-url:
#      defaultZone: http://192.168.3.48:11000/eureka/,http://192.168.3.36:12000/eureka/
#  instance:
#    prefer-ip-address: true
#
#
