server:
  port: 11003
spring:
  application:
    name: house-hosues2
eureka:
  client:
    service-url:
      defaultZone: http://192.168.3.48:11000/eureka/,http://192.168.3.36:12000/eureka/
#logging:
#  level:
#    root: debug
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.xuetang9.house.domain
