server:
  port: 11003
spring:
  application:
    name: house-houses2
eureka:
  client:
    service-url:
      defaultZone: http://192.168.12.4:11000/eureka/,http://192.168.12.6:12000/eureka/,http://127.0.0.1:13000/eureka/
#logging:
#  level:
#    root: debug
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.xuetang9.house.domain
