export default {
    namespaced:true,
    state:{
        houseList:[
            {
                id:1,
                pictureUrl:"assets/images/property/property-1.jpg",
                square:550,
                roomNumber:6,
                bathroomNumber:4,
                garageNumber:3,
                title:'江南宅院',
                address:'锦江区东大街下东大街568号',
                rentType:1,
                price:550,
                leaseType:1,
                isHot:1,
                isSpecial:0,
                description: 'Friuli-Venezia Giflia is the best theme for elit, sed door dolor sit amet, conse ctetur adipiscing elit, sed do eiud in tempor incididun'
            },
            {
                id:2,
                pictureUrl:"assets/images/property/property-2.jpg",
                square:550,
                roomNumber:6,
                bathroomNumber:4,
                garageNumber:3,
                title:'木马山别墅',
                address:'城北大道450附22号',
                rentType:2,
                price:2550,
                leaseType:1,
                isHot:1,
                isSpecial:0,
                description: 'Marvel de Villa is the best theme for elit, sed door dolor sit amet, conse ctetur adipiscing elit, sed do eiud in tempor incididun'
            },
            {
                id:3,
                pictureUrl:"assets/images/property/property-3.jpg",
                square:550,
                roomNumber:6,
                bathroomNumber:4,
                garageNumber:3,
                title:'皇家一号公寓',
                address:'锦江区福字街215号',
                rentType:1,
                price:550,
                leaseType:1,
                isHot:1,
                isSpecial:0,
                description: 'Ruposi Bangla Cottage is the best theme for elit, sed door dolor sit amet, conse ctetur adipiscing elit, sed do eiud in tempor incididun'
            },
            {
                id:4,
                pictureUrl:"assets/images/property/property-4.jpg",
                square:550,
                roomNumber:6,
                bathroomNumber:4,
                garageNumber:3,
                title:'龙城一号别墅',
                address:'龙泉驿区南山大道333号附12号',
                rentType:1,
                price:550,
                leaseType:1,
                isHot:1,
                isSpecial:0,
                description: 'MayaKanon de Villa is the best theme for elit, sed door dolor sit amet, conse ctetur adipiscing elit, sed do eiud in tempor incididun'
            },
            {
                id:5,
                pictureUrl:"assets/images/property/property-5.jpg",
                square:550,
                roomNumber:6,
                bathroomNumber:4,
                garageNumber:3,
                title:'春天花园别墅',
                address:'金牛区琴台西路668号',
                rentType:2,
                price:2550,
                leaseType:1,
                isHot:1,
                isSpecial:0,
                description: 'Azorex de South Villa is the best theme for elit, sed door dolor sit amet, conse ctetur adipiscing elit, sed do eiud in tempor incididun'
            },
            {
                id:6,
                pictureUrl:"assets/images/property/property-6.jpg",
                square:550,
                roomNumber:6,
                bathroomNumber:4,
                garageNumber:3,
                title:'万科西山别墅',
                address:'高新区蜀都大道12号',
                rentType:1,
                price:550,
                leaseType:1,
                isHot:1,
                isSpecial:0,
                description: 'Radison de Villa is the best theme for elit, sed door dolor sit amet, conse ctetur adipiscing elit, sed do eiud in tempor incididun'
            }
        ]
    },
    getters:{
        houseList: state => state.houseList
    },
    mutations:{},
    actions:{},
    modules:{}
}