package com.xuetang9.house.houselogin.domain;

import java.util.ArrayList;
import java.util.List;

public class UserTypeExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table user_type
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table user_type
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table user_type
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_type
     *
     * @mbg.generated
     */
    public UserTypeExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_type
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_type
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_type
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_type
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_type
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_type
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_type
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_type
     *
     * @mbg.generated
     */
    public UserTypeExample orderBy(String orderByClause) {
        this.setOrderByClause(orderByClause);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_type
     *
     * @mbg.generated
     */
    public UserTypeExample orderBy(String ... orderByClauses) {
        StringBuffer sb = new StringBuffer();
        for (int i = 0; i < orderByClauses.length; i++) {
            sb.append(orderByClauses[i]);
            if (i < orderByClauses.length - 1) {
                sb.append(" , ");
            }
        }
        this.setOrderByClause(sb.toString());
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_type
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_type
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria(this);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_type
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_type
     *
     * @mbg.generated
     */
    public static Criteria newAndCreateCriteria() {
        UserTypeExample example = new UserTypeExample();
        return example.createCriteria();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_type
     *
     * @mbg.generated
     */
    public UserTypeExample when(boolean condition, IExampleWhen then) {
        if (condition) {
            then.example(this);
        }
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_type
     *
     * @mbg.generated
     */
    public UserTypeExample when(boolean condition, IExampleWhen then, IExampleWhen otherwise) {
        if (condition) {
            then.example(this);
        } else {
            otherwise.example(this);
        }
        return this;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table user_type
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andUtIdIsNull() {
            addCriterion("ut_id is null");
            return (Criteria) this;
        }

        public Criteria andUtIdIsNotNull() {
            addCriterion("ut_id is not null");
            return (Criteria) this;
        }

        public Criteria andUtIdEqualTo(Integer value) {
            addCriterion("ut_id =", value, "utId");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table user_type
         *
         * @mbg.generated
         */
        public Criteria andUtIdEqualToColumn(UserType.Column column) {
            addCriterion(new StringBuilder("ut_id = ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andUtIdNotEqualTo(Integer value) {
            addCriterion("ut_id <>", value, "utId");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table user_type
         *
         * @mbg.generated
         */
        public Criteria andUtIdNotEqualToColumn(UserType.Column column) {
            addCriterion(new StringBuilder("ut_id <> ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andUtIdGreaterThan(Integer value) {
            addCriterion("ut_id >", value, "utId");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table user_type
         *
         * @mbg.generated
         */
        public Criteria andUtIdGreaterThanColumn(UserType.Column column) {
            addCriterion(new StringBuilder("ut_id > ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andUtIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("ut_id >=", value, "utId");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table user_type
         *
         * @mbg.generated
         */
        public Criteria andUtIdGreaterThanOrEqualToColumn(UserType.Column column) {
            addCriterion(new StringBuilder("ut_id >= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andUtIdLessThan(Integer value) {
            addCriterion("ut_id <", value, "utId");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table user_type
         *
         * @mbg.generated
         */
        public Criteria andUtIdLessThanColumn(UserType.Column column) {
            addCriterion(new StringBuilder("ut_id < ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andUtIdLessThanOrEqualTo(Integer value) {
            addCriterion("ut_id <=", value, "utId");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table user_type
         *
         * @mbg.generated
         */
        public Criteria andUtIdLessThanOrEqualToColumn(UserType.Column column) {
            addCriterion(new StringBuilder("ut_id <= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andUtIdIn(List<Integer> values) {
            addCriterion("ut_id in", values, "utId");
            return (Criteria) this;
        }

        public Criteria andUtIdNotIn(List<Integer> values) {
            addCriterion("ut_id not in", values, "utId");
            return (Criteria) this;
        }

        public Criteria andUtIdBetween(Integer value1, Integer value2) {
            addCriterion("ut_id between", value1, value2, "utId");
            return (Criteria) this;
        }

        public Criteria andUtIdNotBetween(Integer value1, Integer value2) {
            addCriterion("ut_id not between", value1, value2, "utId");
            return (Criteria) this;
        }

        public Criteria andUtNameIsNull() {
            addCriterion("ut_name is null");
            return (Criteria) this;
        }

        public Criteria andUtNameIsNotNull() {
            addCriterion("ut_name is not null");
            return (Criteria) this;
        }

        public Criteria andUtNameEqualTo(String value) {
            addCriterion("ut_name =", value, "utName");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table user_type
         *
         * @mbg.generated
         */
        public Criteria andUtNameEqualToColumn(UserType.Column column) {
            addCriterion(new StringBuilder("ut_name = ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andUtNameNotEqualTo(String value) {
            addCriterion("ut_name <>", value, "utName");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table user_type
         *
         * @mbg.generated
         */
        public Criteria andUtNameNotEqualToColumn(UserType.Column column) {
            addCriterion(new StringBuilder("ut_name <> ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andUtNameGreaterThan(String value) {
            addCriterion("ut_name >", value, "utName");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table user_type
         *
         * @mbg.generated
         */
        public Criteria andUtNameGreaterThanColumn(UserType.Column column) {
            addCriterion(new StringBuilder("ut_name > ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andUtNameGreaterThanOrEqualTo(String value) {
            addCriterion("ut_name >=", value, "utName");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table user_type
         *
         * @mbg.generated
         */
        public Criteria andUtNameGreaterThanOrEqualToColumn(UserType.Column column) {
            addCriterion(new StringBuilder("ut_name >= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andUtNameLessThan(String value) {
            addCriterion("ut_name <", value, "utName");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table user_type
         *
         * @mbg.generated
         */
        public Criteria andUtNameLessThanColumn(UserType.Column column) {
            addCriterion(new StringBuilder("ut_name < ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andUtNameLessThanOrEqualTo(String value) {
            addCriterion("ut_name <=", value, "utName");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table user_type
         *
         * @mbg.generated
         */
        public Criteria andUtNameLessThanOrEqualToColumn(UserType.Column column) {
            addCriterion(new StringBuilder("ut_name <= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andUtNameLike(String value) {
            addCriterion("ut_name like", value, "utName");
            return (Criteria) this;
        }

        public Criteria andUtNameNotLike(String value) {
            addCriterion("ut_name not like", value, "utName");
            return (Criteria) this;
        }

        public Criteria andUtNameIn(List<String> values) {
            addCriterion("ut_name in", values, "utName");
            return (Criteria) this;
        }

        public Criteria andUtNameNotIn(List<String> values) {
            addCriterion("ut_name not in", values, "utName");
            return (Criteria) this;
        }

        public Criteria andUtNameBetween(String value1, String value2) {
            addCriterion("ut_name between", value1, value2, "utName");
            return (Criteria) this;
        }

        public Criteria andUtNameNotBetween(String value1, String value2) {
            addCriterion("ut_name not between", value1, value2, "utName");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table user_type
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {
        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table user_type
         *
         * @mbg.generated
         */
        private UserTypeExample example;

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table user_type
         *
         * @mbg.generated
         */
        protected Criteria(UserTypeExample example) {
            super();
            this.example = example;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table user_type
         *
         * @mbg.generated
         */
        public UserTypeExample example() {
            return this.example;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table user_type
         *
         * @mbg.generated
         */
        @Deprecated
        public Criteria andIf(boolean ifAdd, ICriteriaAdd add) {
            if (ifAdd) {
                add.add(this);
            }
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table user_type
         *
         * @mbg.generated
         */
        public Criteria when(boolean condition, ICriteriaWhen then) {
            if (condition) {
                then.criteria(this);
            }
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table user_type
         *
         * @mbg.generated
         */
        public Criteria when(boolean condition, ICriteriaWhen then, ICriteriaWhen otherwise) {
            if (condition) {
                then.criteria(this);
            } else {
                otherwise.criteria(this);
            }
            return this;
        }

        @Deprecated
        public interface ICriteriaAdd {
            /**
             * This method was generated by MyBatis Generator.
             * This method corresponds to the database table user_type
             *
             * @mbg.generated
             */
            Criteria add(Criteria add);
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table user_type
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }

    public interface ICriteriaWhen {
        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table user_type
         *
         * @mbg.generated
         */
        void criteria(Criteria criteria);
    }

    public interface IExampleWhen {
        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table user_type
         *
         * @mbg.generated
         */
        void example(com.xuetang9.house.houselogin.domain.UserTypeExample example);
    }
}