#spring:
#  application.name: house-login
#  datasource:
#    druid.url: jdbc:mysql://127.0.0.1:3306/house?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&verifyServerCertificate=false&useSSL=false&allowPublicKeyRetrieval=true
#    druid.driver-class-name: com.mysql.cj.jdbc.Driver
#    druid.username: root
#    druid.password: 1995WangZhiHao
#  redis:
#    host: 8.129.191.202
#    port: 6379
#    lettuce:
#      pool.max-wait: 100000
#      pool.max-idle: 10
#      pool.max-active: 100
#    timeout: 5000
#
#server.port: 11001
#eureka.client.service-url.defaultZone: http://192.168.3.48:11000/eureka/,http://192.168.3.36:12000/eureka/,http://127.0.0.1:13000/eureka/